### PR TITLE
Fix AddonManager/FileUtils imports

### PR DESCRIPTION
**Pull request by waresnew**
The script has stopped working ever since I updated Firefox Developer Edition from v135.0 to 136.0a2

The error in the browser console was "Components.utils.import is not a function"

An alternative way to import AddonManager and FileUtils is with ChromeUtils.importESModule, and by specifying the filename of the module .mjs file found here: https://searchfox.org/mozilla-central/source/toolkit/modules

Also, the import for FileUtils needs to be hoisted out of the try block as otherwise the browser errors that FileUtils isn't defined (not sure why this didn't error before I updated)

If this PR is merged along with #3 then the script works again (at least for me)

Also this script has been really helpful for my setup. Thanks for releasing it!

### CODE REVIEW

**Comment by crmky** [comment]
Just to add some references here, the Firefox change was caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1881888.

**Comment by ouqilbo** [comment]
I've no idea why you'd be using this script while simultaneously using Dev Edition, which is the sole Firefox version that can load and persist temporary extensions using unsigned xpis 😭 but I really thank you as you saved me a lot of time now that this has made it into the stable release

**Comment by waresnew** [comment]
> I've no idea why you'd be using this script while simultaneously using Dev Edition, which is the sole Firefox version that can load and persist temporary extensions using unsigned xpis 😭 but I really thank you as you saved me a lot of time now that this has made it into the stable release

i'm running a modified version of an extension but still want updates from the original version, so i have to pull from their github and build it periodically
so i have to reload the extension every time it updates to refresh the changes
